### ISSUE TITLE
1.1.0.0 should be a major version bump

### ISSUE THREAD

**Issue by singpolyma** [haskell-opengl/StateVar#3]
Should it not?  The API broke backwards compatibility so that my packages no longer compile against this version.

**Comment by svenpanne** [comment]
Well, 1.0.1.1 => 1.1.0.0 *was* a major version bump: Major version 1.0 was bumped to 1.1, minor version 1 was reset to 0, patch level 1 was reset to 0, too.

**Comment by singpolyma** [comment]
Uhh... so, a two-part major version?  Not sure I've seen that before, but ok.  I'll keep that in mind for this package in the future.

**Comment by svenpanne** [comment]
That's at least what I read out of the PVP, but that was years ago, and I bumped the versions of all my packages according to that for years. Perhaps the interpretation is different today, perhaps not, I don't care too much about that: Personally, I think the whole notion of naive linear versioning is fundamentally broken, anyway...

P.S.: Hmmm, I think my interpretation is still correct, regardless of what any wiki page perhaps says. Looking at e.g. http://hackage.haskell.org/package/Cabal, the first part has *never* changed, and I highly doubt that it has a stable API for 9 years. Same for e.g. http://hackage.haskell.org/package/binary or http://hackage.haskell.org/package/vector.
