### ISSUE TITLE
Requirement for HasUpdate is the wrong type

### ISSUE THREAD

**Issue by Zemyla** [haskell-opengl/StateVar#4]
The current prerequisite for `HasUpdate` is

```haskell
class HasSetter t a => HasUpdate t a b | t -> a b
```

but it should instead be

```haskell
class HasSetter t b => HasUpdate t a b | t -> a b
```

This is because `\u b -> u $~ const b` should have the same requirements as `$=`, but it doesn't. This hasn't been detected until now because everything so far has had the get and set variables the same.

Steps to reproduce:

```haskell
> :t \u b -> (u $~ (const b)) `asTypeOf` (u $= b)
-- expected: (MonadIO m, HasUpdate t a b) => t -> b -> m ()
\u b -> (u $~ (const b)) `asTypeOf` (u $= b) :: (MonadIO m, HasUpdate t a a) => t -> a -> m ()

**Comment by svenpanne** [comment]
@ekmett Could you have a look at the commit, please? The proposed fix looks OK to me, I just want to be sure before I do a Hackage release...

**Comment by ekmett** [comment]
Looks good to me.
