### ISSUE TITLE
builing but not installing

### ISSUE THREAD

**Issue by djduke** [haskell-opengl/StateVar#9]
This may be a library issue or ghc issue. I'm working with ghc-8.10.4 as my end goal is to install libraries where this is the latest ghc version with reported builds, I'm n OSX. When I built StateVar-1.2.1 using cabal configure/build/install  I got:
"Cannot build the executables in the package StateVar because it does
not contain any executables. Check the .cabal file for the package and make
sure that it properly declares the components that you expect."
A bit of googling suggested this is/was a known issue and that I should try using --lib
I did that and it seemed to build okay, however the library does not appear
when running ghc-pkg list
This is the end of a long chain of failures:
I need StateVar to build primitive, to build vector to build cairo/wx on which two of my  projects depend..
Apols that theversion if the issue has been previously resolved, then I have a different problem- it would
be helpfu to know oe way or the other...

**Comment by svenpanne** [comment]
Well, without seeing the concrete steps you've tried it's a bit hard to guess what's going wrong. `StateVar` works with 8.10.3 (https://travis-ci.org/github/haskell-opengl/StateVar/jobs/751982681) as you can see in the latest Travis CI run (https://travis-ci.org/github/haskell-opengl/StateVar). I doubt that 8.10.4 is different, it contained only minor bug fixes. On Stackage there is even a version with 8.10.4: https://www.stackage.org/nightly-2021-02-12/package/StateVar-1.2.1

My guess is that you are actually fighting against the tools (GHC/Cabal/Stack/...), which try very hard nowadays to _not_ install things globally next to your GHC, which would lead to dependency hell sooner or later. The question is: What are you trying to achieve? Why do you think is it necessary to install things globally? Probably you are trying to solve a completely different problem.

**Comment by djduke** [comment]
Yes I may be fighting the 'now preferred' way. However my understanding was that it should still be possible to install packages globally not least so that they can be sim ply imported into a ghci session.. cf the discussion today on Haskell Cafe the  with topic "Global Package Install". My ultimate  goal was to install ThreadScope. I took a fresh git check out of its source and tried stack build. This failed due to
_hs_iconv in libHSbase-4.13.0.0.a(iconv.o).
This may be an issue peculiar to OSX and I should probably raise this as a separate issue with  the threadscope
team . However I wanted to try and unpick it but find stack a bit of an opaque black-box so I thought to try assebling incrementally via cabal which I have every expectation should still work. In working back from cairo I found the issue with StateVar. For information Here is a transcript:
'cabal.project.local' file already exists. Now overwriting it.
Resolving dependencies...
Up to date
bash-3.2$ cabal build
Up to date
bash-3.2$ cabal install

wrote tarball sdist to
/Users/scsdjd/Haskell/Packages/StateVar-1.2.1/dist-newstyle/sdist/StateVar-1.2.1.tar.gz
Resolving dependencies...
cabal: Cannot build the executables in the package StateVar because it does
not contain any executables. Check the .cabal file for the package and make
sure that it properly declares the components that you expect.

bash-3.2$ exit

Script done on Thu Feb 18 18:44:48 2021

**Comment by svenpanne** [comment]
Perhaps an alias/wrapper to call `stack ghci` or `stack exec ghci` will help you? I have an alias for the latter and find it quite helpful. `cabal` probably has a similar mechanism, but I don't use cabal at all.

Anyway, this is not a `StateVar` problem, so I'm closing this issue.
